### PR TITLE
fix setting default value and throwing errors case param type is boolean

### PR DESCRIPTION
**Pull request by piya23300**
1 when param type is boolean but  param value isn't boolean value. it will set param value to nil
I think it should throw error as same as other param type.
 
example

```
action controller receive `param[:test_boolean] = '123456'`
param! :test_boolean, :boolean
param[:test_boolean] # return nil
```

***

2 when param type is boolean and set default value is boolean

you code is `options[:default].present?` to check default presence
when `default: boolean` ? it's wrong.

example

```
param! :test_boolean, :boolean, default: false
```

`options[:default].present?` will return `false`
this param will not be set to `false` value

### CODE REVIEW

**Comment by stantoncbradley** [comment]
we have run into these issues as well.  Being able to set boolean defaults to false would be very helpful.  Right now I have to check if param[:my_boolean] == true to avoid null constraints in the DB :/

**Comment by carryall** [comment]
@stantoncbradley so this pull request should fix that issue, isn't it?

**Comment by stantoncbradley** [comment]
@carryall yes, and the test specs show this desired behavior.

**Comment by piya23300** [comment]
@stantoncbradley Would you merge this PR and update gem version?

**Comment by carryall** [comment]
@nicolasblanco @stantoncbradley Is the 0.9 version on RubyGem included this fix ?
https://rubygems.org/gems/rails_param/versions/0.9.0
And is it ok to update the gem from 0.0.3 to 0.9 ?

**Pull request merged**
