### PR TITLE
Keep only necessary rails gem dependencies

### PR DESCRIPTION
**Pull request by alexeyschepin**
## Description
As discussed in https://github.com/nicolasblanco/rails_param/issues/87 it makes sense to keep only necessary rails dependencies. It will allow to use this gem without the whole rails suite

## Todos
List any remaining work that needs to be done, i.e:
- [ ] Tests
- [ ] Documentation

## Additional Notes
Optional section

### CODE REVIEW

**Review by iMacTia — APPROVED** [review]
I had a look at the CI logs and I don't see Rails in the result list from `bundle install`, so this looks good 🙌 !

**Comment by alexeyschepin** [comment]
@iMacTia great! Thanks for such a quick feedback. Do you know when it could be released?

**Comment by iMacTia** [comment]
I'd say let's ship it 🚢 !

**Comment by iMacTia** [comment]
@alexeyschepin there you go! https://rubygems.org/gems/rails_param/versions/1.3.0
It would be great to know if it worked 👍

**Comment by alexeyschepin** [comment]
@iMacTia amazing, it seems to be working just fine

**Pull request merged**
