### PR TITLE
Add parameter name to error message for easier debugging

### PR DESCRIPTION
**Pull request by kmcgaire**
### Description

As PR mentions. This gives better error messages to the validations fails to tell the developer which parameter the validation failed on.

### CODE REVIEW

**Comment by kmcgaire** [comment]
@nicolasblanco can you take a look at this?

**Comment by kmcgaire** [comment]
@nicolasblanco bump

**Comment by nicolasblanco** [comment]
Hey, sorry to be late to respond.

What do you think of also passing the attribute name as a symbol or string as a parameter of InvalidParameterError?

**Comment by kmcgaire** [comment]
@nicolasblanco I'm not sure what you mean.
```ruby
rescue InvalidParameterError => exception
        exception.param ||= name
        exception.options ||= options
        raise exception
      end
```
It looks like the param already gets set here

**Comment by kmcgaire** [comment]
@nicolasblanco bump

**Comment by kmcgaire** [comment]
@nicolasblanco bump

**Comment by trantorLiu** [comment]
Can't wait for this!!

**Comment by nicolasblanco** [comment]
@kmcgaire : 👍

**Pull request merged**
