### PR TITLE
Check param's presence before transforming its value

### LINKED ISSUE #59: when nil in required param `transform` fails
## Basic Info

* rails_param Version: 0.11.0
* Ruby Version: 2.6
* Rails Version: 4.2.10

The following is a required param, if the param is missing a `Parameter type is required (400)` exception should be thrown. However, the transform executes before the required validation and to_sym throws `undefined method to_sym for nil:NilClass`.

`param! :type, String, required: true, in: %i[quarterly annual], transform: :to_sym
`

### PR DESCRIPTION
**Pull request by kmathesw**
## Description
Performs `required` validation before `transform`-ing the value to prevent `NilClass` error.
Fixes #59

### CODE REVIEW

**Review by iMacTia — APPROVED** [review]
Thank you @kmathesw, the fix makes sense and I can see the test coverage is fine, although it seems like we have some issues with the Travis build.
Running tests locally for all the combinations is going to be a pain, so please bear with me while I switch over to GitHub Actions.

**Comment by iMacTia** [comment]
@kmathesw would you mind pulling/rebasing from master? I've just merged in #61 that should fix the tests 👍

**Comment by kmathesw** [comment]
> @kmathesw would you mind pulling/rebasing from master? I've just merged in #61 that should fix the tests 👍

@iMacTia Done.

**Comment by iMacTia** [comment]
Thanks @kmathesw, all tests green 🎉 !
LGTM

**Pull request merged**
