### PR TITLE
coerce Array type

### PR DESCRIPTION
**Pull request by adisos**

### CODE REVIEW

**Comment by LIQRGV** [comment]
I think you cant change the implementation without change the test.
Also, why you want to coerce it ?
Could you give the use case ?

**Comment by adisos** [comment]
I'll add tests.

@LIQRGV 
Because if you set array type you should get empty array, not nil. IMHO

**Comment by iMacTia** [comment]
@adisos thanks for looking into this.
Short answer: I believe you should use the `default` option in this case.

Long answer:
If no value is provided for the array parameter, then `param` will be nil.
Changing that automatically to `[]` may cause unexpected behaviours.
However, if you use the `default` option, then you can specify the value you would like to see in case the parameter is missing or `nil`.
Obviously, the same goes for hashes (`{}`).

I hope this makes sense and I'm closing the PR, but if it doesn't please let me know and we can reopen.

**Comment by adisos** [comment]
@iMacTia 
yeah, that makes sense.

**Pull request closed without merging**
