### PR TITLE
Support 'blank' for ActionController::Parameters

### PR DESCRIPTION
**Pull request by zentooo**
## Description

My use case:

```ruby
    # This is RESTful JSON API for updating operator resource (PATCH /operators/:operator_id)
    def update
      param! :operator_id, Integer, required: true
      param! :operator, Hash, required: true, blank: false # this 'blank: false' does not work because params[:operator] is an instance of ActionController::Parameters
      param! :update_mask, Array, required: true

      operator = Operator.find_by(id: params[:operator_id])
      # omitted
      return render json: operator
    end
```

### CODE REVIEW

**Comment by iMacTia** [comment]
@zentooo it seems like we were missing support for the new Rails 5 `ActionController::Parameters`, and your PR is adding them correctly.
Thanks also for improving and extending the tests.
The failure in the CI is not your fault and it's something I'm investigating, so your tests should pass after that is fixed

**Comment by zentooo** [comment]
@iMacTia 
Thank you for merging PR.
Could you release a new version of gem?

**Comment by iMacTia** [comment]
@zentooo v0.11.0 should now be available on Rubygems 🎉

**Comment by zentooo** [comment]
@iMacTia Thank you!

**Pull request merged**
